name: "Lio deploy action"
description: "Deploy your app to lamp.io platform"
author: https://www.lamp.io/
inputs:
  auth_token:
    required: true
    description: "Set your auth token for lamp.io"
  app_id:
    required: true
    description: "Your lamp.io App Id"
runs:
  using: "docker"
  image: 'Dockerfile'
  args:
    - ${{ inputs.auth_token }}
    - ${{ inputs.app_id }}